{"uuid": "6f93eae0-dbfd-4908-8712-3754de995187", "children": ["f997dde0-e80a-4958-8484-af7c91d8fbea"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "ValueError: response body:\n{\"message\":\"API rate limit exceeded for 177.73.97.182. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)\",\"documentation_url\":\"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting\"}\n\nrequest url:\nhttps://api.github.com/repos/mozilla/geckodriver/releases/latest\nresponse headers:\n{'Date': 'Wed, 23 Apr 2025 21:46:56 GMT', 'Server': 'Varnish', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'deny', 'X-XSS-Protection': '1; mode=block', 'Content-Security-Policy': \"default-src 'none'; style-src 'unsafe-inline'\", 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-RateLimit-Used, X-RateLimit-Resource, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset', 'Content-Type': 'application/json; charset=utf-8', 'Referrer-Policy': 'origin-when-cross-origin, strict-origin-when-cross-origin', 'X-GitHub-Media-Type': 'github.v3; format=json', 'X-RateLimit-Limit': '60', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1745445263', 'X-RateLimit-Resource': 'core', 'X-RateLimit-Used': '60', 'Content-Length': '279', 'X-GitHub-Request-Id': 'D726:181E12:14D4D9C:1878955:68095FD0'}\n\n", "trace": "  File \"/usr/local/lib/python3.9/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/_pytest/fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/app/conftest.py\", line 72, in driver\n    driver = setup_browser(browser, headless)\n  File \"/app/conftest.py\", line 44, in setup_browser\n    service=FirefoxService(GeckoDriverManager().install()), options=options\n  File \"/usr/local/lib/python3.9/site-packages/webdriver_manager/firefox.py\", line 39, in install\n    driver_path = self._get_driver_binary_path(self.driver)\n  File \"/usr/local/lib/python3.9/site-packages/webdriver_manager/core/manager.py\", line 35, in _get_driver_binary_path\n    binary_path = self._cache_manager.find_driver(driver)\n  File \"/usr/local/lib/python3.9/site-packages/webdriver_manager/core/driver_cache.py\", line 105, in find_driver\n    driver_version = self.get_cache_key_driver_version(driver)\n  File \"/usr/local/lib/python3.9/site-packages/webdriver_manager/core/driver_cache.py\", line 151, in get_cache_key_driver_version\n    return driver.get_driver_version_to_download()\n  File \"/usr/local/lib/python3.9/site-packages/webdriver_manager/core/driver.py\", line 48, in get_driver_version_to_download\n    return self.get_latest_release_version()\n  File \"/usr/local/lib/python3.9/site-packages/webdriver_manager/drivers/firefox.py\", line 29, in get_latest_release_version\n    resp = self._http_client.get(\n  File \"/usr/local/lib/python3.9/site-packages/webdriver_manager/core/http.py\", line 36, in get\n    self.validate_response(resp)\n  File \"/usr/local/lib/python3.9/site-packages/webdriver_manager/core/http.py\", line 19, in validate_response\n    raise ValueError(\n"}, "start": 1745444816310, "stop": 1745444816906}], "start": 1745444816310, "stop": 1745444816920}